### ISSUE TITLE
Caught fish can't be sold in EMF Shop.

### ISSUE THREAD

**Issue by mibby** [Oheers/EvenMoreFish#144]
EMF dev 58 
https://ci.codemc.io/view/All/job/Oheers/job/EvenMoreFish/58/

Caught fish cannot be sold in EMF shop for money. Broke from the NBT commits?

Config.yml
```
# Setting this to false disables /emf shop and money rewards from competitions. It's unlikely
# you'll want to do this but it is possible.
enable-economy: true

# For customizing the /emf shop GUI
gui:
  # Fills the empty slots of a normal /emf shop
  filler: GRAY_STAINED_GLASS_PANE
  # Fills the empty slots of /emf shop when there's an error (i.e. the player trying to sell nothing)
  filler-error: RED_STAINED_GLASS_PANE
  # The item for the player to click to sell their fish
  sell-item: GOLD_INGOT
  # The slot to put the item in on the bottom row, accepts values 1-9 inclusive.
  sell-slot: 4
  # The item for the player to click to automatically sell all their fish
  sell-all-item: COD_BUCKET
  # The slot to put the item in on the bottom row, accepts values 1-9 inclusive.
  sell-all-slot: 6
  # The item for the player to click to confirm selling their fish
  sell-item-confirm: GOLD_BLOCK
  # The item for the player to click to confirm selling all of their fish
  sell-all-item-confirm: TROPICAL_FISH_BUCKET
  # The item shown to the player when an error occurs (trying to sell nothing of value from the gui)
  sell-item-error: REDSTONE_BLOCK
  # The item shown to the player when an error occurs (trying to sell nothing of value from their inventory)
  sell-all-item-error: SALMON_BUCKET
  # How many rows the selling area of the GUI should be (max 5, min 1)
  size: 3
  # Should the items be dropped(false) or sold(true) when a player exits an inventory?
  sell-over-drop: false
```

Default fish.yml & rarities.yml for worth values.
