### ISSUE TITLE
Suggestion: Config options to create biome presets in some way

### ISSUE THREAD

**Issue by moolicc** [Oheers/EvenMoreFish#231]
Hi! I'm currently maintaining a server for me and some friends running the EvenMoreFish plugin.
I'm also running Terra with their default generation config, which adds a plethora of biomes to configure.
It's honestly been kind of a pain in the neck to go through each fish and specify what feels like a thousand tropical/subtropical/etc biomes.

So what I envision is some way to configure the requirements.biome section of a fish to allow for some kind of "biome category" or something, which itself would refer to a configured set of biomes.

Implementation Example:
```yml
fish:
  Tropical Fish:
    requirements:
        biome-groups:
          - Tropical_Salt_Water
          - Tropical_Fresh_Water
  Sea Snail:
    requirements:
        biome-groups:
          - Tropical_Salt_Water

biome-groups:
  Tropical_Salt_water:
    - TROPICAL_OCEAN
    - CORAL_OCEAN
    # ...
  Tropical_Fresh_Water:
    - JUNGLE
    - BAMBOO_JUNGLE
    # ...
```

Let me know what you think, and if you'd accept a PR I can donate some of my time on this and work it out :)
