### ISSUE TITLE
Baits get used even to the baits rarity is not caught

### ISSUE THREAD

**Issue by noaskers** [Oheers/EvenMoreFish#331]
```
baits:
  Brood:
    item:
      material: BREAD
      # How should this be displayed in game?
      displayname: "&#eb8f34Brood Aas"
    glowing: true
    # This can be used in the lore format to create a consistent colour theme.
    bait-theme: "&#eb8f34"
    # This lists the fish that are attracted to this bait (make sure to specify the rarity and ensure there's no typos)
    rarities:
      - "Normaal"
    # How likely should it be to find this bait when they're caught.
    catch-weight: 250
    # When more than 1 types of baits are applied, how likely is it that this one should be used?
    application-weight: 150
    # How many of this bait can be applied to a rod at once?
    max-baits: 1
  Garnalen:
    item:
      material: RABBIT_FOOT
      # How should this be displayed in game?
      displayname: "&#ff7777Garnalen Aas"
    glowing: true
    # This can be used in the lore format to create a consistent colour theme.
    bait-theme: "&#ff7777"
    # This lists the fish that are attracted to this bait (make sure to specify the rarity and ensure there's no typos)
    rarities:
      - "Normaal"
      - "Unieke"
    # How likely should it be to find this bait when they're caught.
    catch-weight: 100
    # When more than 1 types of baits are applied, how likely is it that this one should be used?
    application-weight: 150
    # How many of this bait can be applied to a rod at once?
    max-baits: 1

  Wormen:
    item:
      material: TADPOLE_BUCKET
      displayname: "&#dbacb4Wormen Aas"
    glowing: true
    bait-theme: "&#dbacb4"
    rarities:
      - "Unieke"
      - "Epische"
    catch-weight: 20
    application-weight: 150
    max-baits: 1

  Slak:
    item:
      material: NAUTILUS_SHELL
      displayname: "&#38ff7aSlakken Aas"
    glowing: true
    bait-theme: "&#38ff7a"
    catch-weight: 20
    application-weight: 40
    rarities:
      - "Tropische"
    max-baits: 1

  Kunstaas:
    item:
      material: TROPICAL_FISH
      displayname: "&#fdca01Kunst Aas"
    glowing: true
    bait-theme: "&#fdca01"
    rarities:
      - "Legendarisch"
    catch-weight: 2
    application-weight: 40
    max-baits: 1
```

I don't really understand why but yeah
