### ISSUE TITLE
[Suggestion (Plugin)]: Rewrite economy support to allow multiple types

### ISSUE THREAD

**Issue by FireML** [Oheers/EvenMoreFish#500]
### Suggestion

Allow multiple economy types to be enabled/disabled by server admins. Also add config for multipliers to apply to these.

Example:
```
# Enable/Disable certain economy types here. Optionally change the multiplier applied to them.
economy: 
  # Vault economy is enabled with a 1x multiplier.
  Vault:
    enabled: true
    multiplier: 1.0
  # PlayerPoints is disabled so is ignored.
  PlayerPoints:
    enabled: false
    multiplier: 1.0
  ## GriefPrevention is enabled with a 0.25x multiplier
  GriefPrevention:
    enabled: false
    multiplier: 0.25
```
With the above config, a fish worth 400 would give 400 vault currency and 100 claim blocks.
