### ISSUE TITLE
[Bug]: Mysql databse don't work

### ISSUE THREAD

**Issue by LixiUnivers** [Oheers/EvenMoreFish#504]
### Contact Details

lixicontacte@gmail.com

### What happened?

Database mysql, does not run the plugin. It only works for sqllite
I use mysql and in /pl, plugin is red.

```yml
database:
  enabled: true
  # Available option are: mysql, sqlite
  type: mysql
  # The address of the database
  # (the port 3306 is automatically added in by default, if different: specify with address:port)
  address: (don't show)
  # The name of the database to store fish data in
  database: (don't show)
  # The table prefix for the database.
  # WARNING: Changing this will create new tables in the database.
  # Only use this during first setup or before migrations.
  # (Or after, but only if you know what you're doing).
  table-prefix: "emf_"
  # Login information
  username: (don't show)
  password: (don't show)
```
### Version

1.7.3

### Server Version

Paper-1.19

### Java Version

17

### Relevant screenshots

![2024-12-04_13 29 23](https://github.com/user-attachments/assets/cbd6207c-1f13-4e55-ac91-8bbc2db87ccf)
